// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'Mui-disabled': string;
  'Mui-focusVisible': string;
  'MuiButton-contained': string;
  'MuiButton-label': string;
  'MuiButton-outlined': string;
  'MuiButton-root': string;
  'MuiButton-text': string;
  's3-button': string;
  's3-icon': string;
}
export const cssExports: CssExports;
export default cssExports;
