export enum ApiErrorMessage {
  UserMismatch = 'Email or password is incorrect',
  UserRemoved = 'User was removed',
  UserInactive = 'User account is inactive',
  UserNotFound = 'No such user found',
  ResetTokenNotFound = 'Token does not exist',
  ResetTokenExpired = 'Token has expired',
  AccessTokenExpired = 'Your login token has expired',
  WrongCurrentPassword = 'Current password is not correct',
  InvalidVersionRequested = "Version doesn't exist",
  InvitationNotFound = "Invitation doesn't exist",
  InvitationAlreadyExists = 'This e-mail has been already invited',
  ItemSoldOut = 'Out of stock',
  VatAlreadyRegistered = "Can't accept this company",
  ProductAlreadyInList = 'Product is already on the list',
  ListNotFound = 'List not found',
  EmailIsAlreadyAssigned = 'E-mail is already assigned',
  ImageAlreadyInMoodboard = 'Image is already in the moodboard',
  PostalCodeCountryMismatch = 'This postalcode does not exist in this country, please contact your administrator',
  UniqueVatValue = 'VatNo already exist',
}
